# PostgreSQL basic config
listen_addresses = '*'
port = 5432

# Para pg_audit
shared_preload_libraries = 'pgaudit'
pgaudit.log = 'all'
pgaudit.log_relation = on
pgaudit.log_level = 'log'
pgaudit.log_parameter = on