name: kefir

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: kefir_db
    command:
      - postgres
      - -c
      - shared_buffers=128MB
      - -c
      - max_connections=20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kefir-network

  backend:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    secrets:
      - spring.datasource.password
      - jwt.secret
    command:
      - --spring.config.import=optional:configtree:/run/secrets/
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kefir_db
      SPRING_DATASOURCE_USERNAME: postgres
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kefir-network

  frontend:
    image: nduarte93/kefir-frontend:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - kefir-network

volumes:
  postgres_data:

networks:
  kefir-network:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

  spring.datasource.password:
    file: ./secrets/spring.datasource.password

  jwt.secret:
    file: ./secrets/jwt.secret