services:
  datadog-agent:
    image: registry.datadoghq.com/agent:latest
    container_name: dd-agent
    pid: "host"
    environment:
      - DD_API_KEY=4d79dd0f6804a25fc4c18dc12dbc5279
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_HOSTNAME=kefir-local
      - DD_SITE=datadoghq.com
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=false
    ports:
      - "8126:8126"
      - "10518:10518"
    volumes:
      - ${HOME}/datadog/conf.d:/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # query
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - grafana

volumes:
  grafana-data:
  tempo-data: