spring.datasource.url=jdbc:postgresql://localhost:5432/kefir_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.properties.hibernate.id.db_structure_naming_strategy=single