spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.web.server.enabled=true
management.metrics.web.server.request.autotime.enabled=true

sns.topic.arn=arn:aws:sns:sa-east-1:373901294333:loan-created-topic

logging.level.org.kefir=INFO
logging.level.software.amazon.awssdk=INFO
logging.level.org.kefir.infrastructure.messaging=INFO
logging.level.root=INFO