spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kefir_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

server.address=0.0.0.0
server.port=${PORT:8080}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.batch.jdbc.initialize-schema=always

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.aop.proxy-target-class=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cache.redis.time-to-live=600000
management.health.redis.enabled=false

management.endpoints.web.exposure.include=health,metrics,prometheus
management.metrics.web.server.enabled=true
management.tracing.service.name=kefir
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTLP_ENDPOINT:http://localhost:4318/v1/traces}
management.observations.annotations.enabled=true

aws.sns.enabled=false
sns.topic.arn=${SNS_KEY}

logging.level.org.kefir=INFO
logging.level.software.amazon.awssdk=INFO
logging.level.org.kefir.infrastructure.messaging=INFO
logging.level.root=INFO
logging.level.org.springframework.batch=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %X{dd.trace_id} %X{dd.span_id} - %m%n
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=${JWT_SECRET}
