# Datos de la base en local
spring.datasource.url=jdbc:postgresql://localhost:5432/Kefir
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Spring Batch
spring.batch.jdbc.initialize-schema=always

# Servidor
server.address=0.0.0.0

# AWS (para pruebas locales)
AWS_ACCESS_KEY_ID=AKIAVODSA7L6TSF44Y7Y
AWS_SECRET_ACCESS_KEY=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
AWS_REGION=sa-east-1

# SNS
sns.topic.arn=arn:aws:sns:sa-east-1:373901294333:loan-created-topic

# Logging
logging.level.org.kefir=INFO
logging.level.software.amazon.awssdk=INFO
logging.level.org.kefir.infrastructure.messaging=INFO
logging.level.root=INFO
logging.level.org.springframework.batch=INFO
